### ISSUE TITLE
Pixelui shouldn't crash if font file not found

### ISSUE THREAD

**Issue by dusk125** [dusk125/pixelui#10]
Currently, if PixelUI.AddTTFFont is called on a file that doesn't exist, the program crashes with an un-helpful error. PixelUI should be updated to check if the font file exists before trying to add it to imgui.

**Comment by cebarks** [comment]
Honestly I think it should panic if it doesn't exist, but it should be a clear error message as to what is happening...

**Comment by dusk125** [comment]
Fair, that's probably what I'll do with a proper message... the problem currently is that the C layer is handling the file open and basically just explodes unhelpfully if the file doesn't exist.

```
panic: Assertion failed!
File: imgui_draw.cpp, Line 1605

Expression: 0


goroutine 6 [running]:
github.com/inkyblackness/imgui-go.glob..func1({0xc00001202c, 0x1}, {0xc000012040, 0xc0000583e0}, 0x0)
```

**Comment by cebarks** [comment]
Oh ya that is an unhelpful message. Can you read the raw file as bytes and pass that the the C layer?

**Comment by dusk125** [comment]
Doesn't look like it, my plan was to just stat the incoming filepath and panic if it doesn't exist, otherwise, pass it down to the imgui layer.
