### ISSUE TITLE
More font support 

### ISSUE THREAD

**Issue by dusk125** [dusk125/pixelui#6]
Currently, pixelui only uses the default imgui font, add a function to add a user font.

**Comment by dusk125** [comment]
Done, just waiting on my Pixel PRs before merging this in.

**Comment by dusk125** [comment]
Pixel PRs have been accepted, closing.

**Comment by nexovec** [comment]
Can you provide any examples of using fonts with this package? Loading fonts directly through imgui crashes the program and using `ui.AddTTFFont` doesn't actually change the font.
